sudo: required
services:
   - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-743577097029"
  bucket_path: ".elasticbeanstalk"
  on:
    branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key:
     secure: "AWS_SECRET_KEY"

